[package]
name = "RustRocket"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
once_cell = "1.8.0"
dirs = "3.0"
xdg = "2.2.0"
egui = "0.27.2"
eframe = "0.27.2"
rayon = "1.10.0"
